name: flutter_bbs
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.0
  cached_network_image: 0.6.0
  crypto: ^2.0.6
  dio: ^2.0.15
  path_provider: ^0.5.0
  #permission_handler: ^3.1.0
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.2.2

  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/c.jpg
    - images/bg_splash.png
    - images/ic_launcher.png

